services:
  meu_app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      INSTANCE_ID: 1
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - meu_postgres_si:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  meu_postgres_si:
  rabbitmq_data:
