services:
  meu_app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      INSTANCE_ID: 1
      LIDER_ID: 1
      PORTA: 8080
    depends_on:
      - db_si
      - rabbitmq

  meu_app2:
    build: .
    env_file:
      - .env2
    ports:
      - "8081:8081"  # Corrija o mapeamento da porta
    environment:
      INSTANCE_ID: 2
      LIDER_ID: 1
      PORTA: 8082  # Use a mesma porta interna
    depends_on:
      - db_si2
      - rabbitmq

  meu_app3:
    build: .
    env_file:
      - .env3
    ports:
      - "8083:8083"  # Corrija o mapeamento da porta
    environment:
      INSTANCE_ID: 3
      LIDER_ID: 1
      PORTA: 8083  # Use a mesma porta interna
    depends_on:
      - db_si3
      - rabbitmq

  db_si:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  db_si2:
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"  # Mapeie a porta interna para 5432

  db_si3:
    image: postgres
    env_file:
      - .env
    ports:
      - "5434:5432"  # Mapeie a porta interna para 5432

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
